### ISSUE TITLE
the data service is throwing a file not found error while trying to fetch 

### ISSUE THREAD

**Issue by deondavis** [kodefoundry/xconf-docker#4] opened 2020-07-03 06:26 UTC
Once all the configurations are done via the UI, tried to fetch the details using a curl command which threw 404 error.
the application selected was STB
The curl command used is 
`curl -w '%{http_code}\n' --connect-timeout 10 -m 10 -o  "/opt/DCMresponse.txt" 'http://<AWS IP>:9092/loguploader/getSettings?estbMacAddress=AA:BB:CC:DD:EE:FF&firmwareVersion=bcm20.1-1234xyz&env=dev&model=RPI&ecmMacAddress=AA:BB:CC:DD:EE:FF&controllerId=2504&channelMapId=2345&vodId=15660'`

trying to test the telemetry exercise from RDK wiki using this docker setup. The slides of Lisbon demo attached below.
[RDK_TechSummit2019_Exercises_206_Telemetry.pdf](https://github.com/kodefoundry/xconf-docker/files/4868078/RDK_TechSummit2019_Exercises_206_Telemetry.pdf)

**Comment by kodefoundry** [comment] 2020-07-04 19:09
I will not be maintaining this repo anymore, since I no longer working on this project anymore. I would suggest you if required please fork out this repo and continue working on it.
Regarding this particular issue, I would suggest you post this in the RDK community web page.

**Comment by kodefoundry** [comment] 2020-07-22 10:03
Hi Davis,
I had a chance to discuss with my old team regarding this. One pointer, maybe try it out.
If you have created the container using my repo, the data service base URL is something like this
http://<AWS IP>:9092/service/

So your API will be effectively

curl -w '%{http_code}\n' --connect-timeout 10 -m 10 -o "/opt/DCMresponse.txt" 'http://<AWS IP>:9092/service/loguploader/getSettings?estbMacAddress=AA:BB:CC:DD:EE:FF&firmwareVersion=bcm20.1-1234xyz&env=dev&model=RPI&ecmMacAddress=AA:BB:CC:DD:EE:FF&controllerId=2504&channelMapId=2345&vodId=15660'

When you get time, try this and please update here if it works

**Comment by deondavis** [comment] 2020-07-27 07:12
this was of no help, think the issue is the data services cannot connect with cassandra

**Comment by kodefoundry** [comment] 2020-07-27 08:02
I suppose you are deploying in AWS, so how are you deploying Cassandra there. Are you trying with AWS MCS, in which case it will not connect. If you have deployed cassandra yourself then do you see any exception logs thrown while the dataservice container is starting up?

**Comment by suraj-mathew** [comment] 2020-07-28 11:02
I have created separate docker for Cassandara, Xconf-angular-admin & data service.
Made the cassandra up and running in one container by changing the configuration to use that container's IP (not the default localhost)
Then from the second container where we setup the Xconf-angular-admin, i have updated the file - [DataServiceConfiguration.java](https://code.rdkcentral.com/r/plugins/gitiles/rdk/components/generic/xconfserver/+/refs/heads/master/dataaccess-core/src/main/java/com/comcast/hesperius/dataaccess/core/config/DataServiceConfiguration.java) to replace "**localhost**:9160" with "**<CASSANDRA_CONTAINER_IP>**:9160"

And upon compilation and the mvn run command , we are getting an exception 

----------------
[WARNING] FAILED o.e.j.m.p.JettyWebAppContext@753aca85{/admin,file:/opt/xconfserver/xconf-angular-admin/src/main/webapp/,STARTING}{file:/opt/xconfserver/xconf-angular-admin/src/main/webapp/}: java.lang.ExceptionInInitializerError
xconfadminvm   | java.lang.ExceptionInInitializerError
xconfadminvm   |     at com.comcast.hesperius.dataaccess.core.cache.CacheConsistencyProvider.<init> (CacheConsistencyProvider.java:82)
xconfadminvm   |     at com.comcast.hesperius.dataaccess.core.util.CoreUtil.<clinit> (CoreUtil.java:161)
.
.
xconfadminvm   | **Caused by: com.comcast.hesperius.dataaccess.core.AstyanaxException: com.netflix.astyanax.connectionpool.exceptions.NoAvailableHostsException: NoAvailableHostsException: [host=None(0.0.0.0):0, latency=0(0), attempts=0]No hosts to borrow from**
xconfadminvm   |     at com.comcast.hesperius.dataaccess.core.dao.util.ExecuteWithUncheckedException.describeKeyspace (ExecuteWithUncheckedException.java:75)
.
.
.
xconfadminvm   | Caused by: com.netflix.astyanax.connectionpool.exceptions.NoAvailableHostsException: NoAvailableHostsException: [host=None(0.0.0.0):0, latency=0(0), attempts=0]No hosts to borrow from
xconfadminvm   |     at com.netflix.astyanax.connectionpool.impl.RoundRobinExecuteWithFailover.<init> (RoundRobinExecuteWithFailover.java:48)
.
.
.
xconfadminvm   | [INFO] Jetty server exiting.

-------------------
So to confirm the connectivity, i created a sample github project that tests the cassandra db connectivity and prints the current date via query execution.

https://github.com/suraj-mathew/cassandra_tester

This sample project was also integrated to the xconf-angular-admin Dockerfile.
When the dockerfile was executed, the sample program was able to connect to the cassandra db in the other container and print the current date.

Thus we confirmed that the connectivity to DB instance is working in multi docker setup using sample program, but not able to connect to the same cassandra DB from the xconf server.

**Comment by kodefoundry** [comment] 2020-07-28 13:36
> I have created separate docker for Cassandara, Xconf-angular-admin & data service.
> Made the cassandra up and running in one container by changing the configuration to use that container's IP (not the default localhost)
> Then from the second container where we setup the Xconf-angular-admin, i have updated the file - [DataServiceConfiguration.java](https://code.rdkcentral.com/r/plugins/gitiles/rdk/components/generic/xconfserver/+/refs/heads/master/dataaccess-core/src/main/java/com/comcast/hesperius/dataaccess/core/config/DataServiceConfiguration.java) to replace "**localhost**:9160" with "**<CASSANDRA_CONTAINER_IP>**:9160"
> 
> And upon compilation and the mvn run command , we are getting an exception
> 
> [WARNING] FAILED o.e.j.m.p.JettyWebAppContext@753aca85{/admin,file:/opt/xconfserver/xconf-angular-admin/src/main/webapp/,STARTING}{file:/opt/xconfserver/xconf-angular-admin/src/main/webapp/}: java.lang.ExceptionInInitializerError
> xconfadminvm | java.lang.ExceptionInInitializerError
> xconfadminvm | at com.comcast.hesperius.dataaccess.core.cache.CacheConsistencyProvider. (CacheConsistencyProvider.java:82)
> xconfadminvm | at com.comcast.hesperius.dataaccess.core.util.CoreUtil. (CoreUtil.java:161)
> .
> .
> xconfadminvm | **Caused by: com.comcast.hesperius.dataaccess.core.AstyanaxException: com.netflix.astyanax.connectionpool.exceptions.NoAvailableHostsException: NoAvailableHostsException: [host=None(0.0.0.0):0, latency=0(0), attempts=0]No hosts to borrow from**
> xconfadminvm | at com.comcast.hesperius.dataaccess.core.dao.util.ExecuteWithUncheckedException.describeKeyspace (ExecuteWithUncheckedException.java:75)
> .
> .
> .
> xconfadminvm | Caused by: com.netflix.astyanax.connectionpool.exceptions.NoAvailableHostsException: NoAvailableHostsException: [host=None(0.0.0.0):0, latency=0(0), attempts=0]No hosts to borrow from
> xconfadminvm | at com.netflix.astyanax.connectionpool.impl.RoundRobinExecuteWithFailover. (RoundRobinExecuteWithFailover.java:48)
> .
> .
> .
> xconfadminvm | [INFO] Jetty server exiting.
> 
> So to confirm the connectivity, i created a sample github project that tests the cassandra db connectivity and prints the current date via query execution.
> 
> https://github.com/suraj-mathew/cassandra_tester
> 
> This sample project was also integrated to the xconf-angular-admin Dockerfile.
> When the dockerfile was executed, the sample program was able to connect to the cassandra db in the other container and print the current date.
> 
> Thus we confirmed that the connectivity to DB instance is working in multi docker setup using sample program, but not able to connect to the same cassandra DB from the xconf server.

Hi Suraj, take a look at Dockerfile line no 119, might provide some clue. The property tells the service to look for 'cassandra', if you want to use IP then you have to change your IP here and rebuild the docker. I had tested this script by deploying in minikube and was actually intended for K8s that's why kept service names. I should have made it an environment variable, might update it if I get time.

**Comment by suraj-mathew** [comment] 2020-07-28 14:21
Thanks for the update.

I have applied the change as mentioned in a comment at https://wiki.rdkcentral.com/pages/viewpage.action?pageId=75826512
and it worked.

> connectionPools.SharedConnectionPool.seeds=\<ip of node running cassandra>

i will do a final round of testing and will update my docker setup.

NOTE: 
Since i am new to dockers, i had created my own dockerfiles from scratch.

**Comment by suraj-mathew** [comment] 2020-07-29 06:22
I was able to deploy the 3 different containers and access the application over browser. Was able to save the data from admin ui as well.

TIPS:
 - We need to change **localhost** value against **rpc_address** and **listen_Address** in <cassandra dir>/conf/cassandra.yaml to the IP of the VM hosting cassandra. Else we wont be able to access it from outside the container. Implies, this needs to be done at the time when we start the cassandra container, not during image creation.
Also, giving the hostname wont work it seems.

 - Similarly, i have parsed and used the IP of the cassandra vm in xconf-admin & data service's **service.properties** and [DataServiceConfiguration.java](https://code.rdkcentral.com/r/plugins/gitiles/rdk/components/generic/xconfserver/+/refs/heads/master/dataaccess-core/src/main/java/com/comcast/hesperius/dataaccess/core/config/DataServiceConfiguration.java) as mentioned in earlier comment. Here also, we need to add the IP at the time when container is started. I have used the **ping** command to find the ip of cassandra instance

>Then from the second container where we setup the Xconf-angular-admin, i have updated the file - DataServiceConfiguration.java to replace "localhost:9160" with "<CASSANDRA_CONTAINER_IP>:9160"

I have uploaded my dockerization project to https://github.com/suraj-mathew/rdk-xconf-multi-docker
My docker files will be looking very basic and hope it will be easier for you to understand.

@kodefoundry  - See if you get any light in resolving your issues

**Closed as completed** 2020-07-29 07:01 UTC
